# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'clean-swift-vip-unit-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for clean-swift-vip-unit-test
  pod 'SnapKit'
  pod 'Alamofire' 
  pod 'Then' 

  target 'clean-swift-vip-unit-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
