# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iostp-charts-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iostp-charts-demo
  pod 'Charts', '~> 3.5'
  pod 'SnapKit'

  target 'iostp-charts-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iostp-charts-demoUITests' do
    # Pods for testing
  end

end
